version: '2'
services:
  mongodb:
    image: mongo:3.4
    command: mongod
    ports:
      - "27017:27017"
    volumes:
      - /data/mongodb:/data/db/
  heyburrito:
    image: chralp/heyburrito:latest
    ports:
      - "3333:3333"
      - "8080:8080"
    environment:
      - BOT_NAME=burritobot
      - DATABASE_DRIVER=mongodb
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DATABASE=heyburrito
      - SLACK_API_TOKEN=xoxb-168936164433-1393442659603-ViCyTgq28xxqq8fRd3d5Umo3
      - "SLACK_EMOJI_INC=:burrito:"
      - "SLACK_EMOJI_INC=:rottenburrito:"
      - SLACK_DAILY_CAP=5
      - DISABLE_EMOJI_DEC=true
    links:
      - mongodb
